# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.6
  - nightly
notifications:
  email: false
before_script:
  - julia -e 'Pkg.clone("https://github.com/oschulz/MultiThreadingTools.jl.git"); Pkg.build("MultiThreadingTools")'
# uncomment the following lines to override the default test script
#script:
#  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#  - julia -e 'Pkg.clone(pwd()); Pkg.build("BAT"); Pkg.test("BAT"; coverage=true)'
after_success:
  # push coverage results to Coveralls
  - julia -e 'cd(Pkg.dir("BAT")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("BAT")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
